---
application:
  name: "myappname"
  project: "project-name"
  organization: "QoveryCommunity"
databases:
- type: "postgresql"
  name: "dbName"
  version: "dbVersion"
routers:
- name: "main-myappname"
  routes:
  - application_name: "myappname"
    paths:
    - "/"
